route:
  receiver: default
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  routes:
    - matchers:
      - severity="critical"
      receiver: slack

receivers:
  - name: default
    email_configs:
      - to: "ops@example.com"
        from: "alertmanager@example.com"
        smarthost: "smtp.example.com:587"
        auth_username: "smtp_user"
        auth_identity: "smtp_user"
        auth_password: "CHANGE_ME"
        require_tls: true

  - name: slack
    slack_configs:
      - api_url_file: /etc/alertmanager/secrets/slack_webhook_url
        channel: "#alerts"
        send_resolved: true
        title: '{{ template "slack.title" . }}'
        text: '{{ template "slack.text" . }}'

templates:
  - '/etc/alertmanager/templates/*.tmpl'
