global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["127.0.0.1:9093"]

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["127.0.0.1:9090"]

  - job_name: node-exporter
    static_configs:
      - targets: ["127.0.0.1:9100"]

  - job_name: cadvisor
    static_configs:
      - targets: ["127.0.0.1:8082"]

  - job_name: blackbox
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs: [] # add targets (URLs) under static_configs when ready
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115

  - job_name: application-metrics
    # Add your app metrics endpoint(s) here (e.g., 127.0.0.1:9101)
    static_configs: []
